Calculadora con forms
facuGarcia/calculatorAppFacu pull request #4
Opened 2021-09-22 18:26 UTC by facuGarcia

## Summary

Como se pidió en la card, se implementó:

- Un servicio POST en Apiary donde va a recibir  input_values este  va a ser un objeto, y va a responder  "Gracias por su mensaje".
- Un botón que te lleve a "/survey" (encuesta).
- - En "/survey" hay un fomulario con:
- - un campo para que el usuario ingrese su nombre y apellido, normalizado tal que  que el usuario no puede ingresar números. 
- - un campo para que el usuario ingrese una devolución de la aplicación.
- - un campo para que el usuario ingrese su numero de teléfono,  normalizado tal que el teléfono no sea mayor a 10 números y que no pueda escribir letras. 
- -botón cancelar:  este va a llevarte a la vista anterior y va a destruir el formulario con los campos que haya completado el usuario, en caso que el usuario haya ingresado su nombre y apellido lo vamos a guardar en el store y  si  vuelve a entrar a la  encuesta  vamos a completar el campo nombre y apellido con el valor que guardamos en el store.
- - botón enviar:  si el usuario completo todos los campos este va a hacer el submit del formulario enviando bajo la key  input_values al servicio los valores que el usuario cargo en la encuesta, si no completo algun campo se deberá  mostrar un mensaje al usuario diciendo que le falto completar un campo.

## Gif

![forms](https://user-images.githubusercontent.com/89090620/134400603-7b30d286-6442-42b9-8c13-78471dfbb9de.gif)

2021-09-23 19:49 UTC, jgarciadelfino approved these changes

2021-10-01 12:20 UTC, facu-rodriguez requested changes
Nice work Facu. 

-----------------------------
Check what happens when I click to edit an expression on /record
![Captura de pantalla de 2021-10-01 08-57-29](https://user-images.githubusercontent.com/68086087/135616264-64325e41-b8c1-47a4-bf94-0b1dc3bfffae.png):
-----------------------------
We aren't getting the operations record from the service. We should make a GET every time we enter into record and in that point fill the "operation record" state if you want.
-----------------------------
fix this:

![expresion borrada](https://user-images.githubusercontent.com/68086087/135617541-35d266b4-891c-4ea0-8642-f88c11d5f0a3.gif)

2021-10-01 12:20 UTC, facu-rodriguez commented on src/app/screens/Survey/layout.js
> +/* eslint-disable react/prop-types */
Delete this entire file and pass everything into the index. There's no need to separate both

2021-10-01 12:20 UTC, facu-rodriguez commented on src/redux/userInfo/reducer.js
> +  primaryActions: ['xd'],
🧐

2021-11-12 16:01 UTC, merged